#include <stdio.h>
#include <math.h>
int main()
{

    char DT='21ST DECEMBER'; //IT IS INVALID'CAUSE WE CAN'T ABLE TO STORE MORE THAN ONE LETTER IN A SINGLE CHARECTER VARRIABLE.
    char DT1='S';//NOW IT IS VALID'CAUSE WE PUT ONE CHARTECTER HERE.
    printf("PRINT DT1%c",DT1); 

    int a;
    b=a; // IT IS INVALID'CAUSE HERE B IS UNIDENTIFIED.
    int A,B;
    B=A; // IT IS VALID BECAUSE HERE WE IDENTIFY THE 'B' AS AN INTEGER.

    int V=3^3; //IT IS VALID IN C PROGRAMME AS A XOR OPERATOR BUT WE CAN'T ABLE TO DO ANY SQUARE WITH IT (IF WE WANT TO DO A SQUARE
    //THEN WE NEED TO INCLUDE MATH.H)
    int V=pow(3,3); //NOW WE CAN DO SQUARE OF A NUMBER OR AN IINTEGER'CAUSE WE ADDED '#INCLUDE <MATH.H>' AND A FUNCTION OF POW.
    printf("PRINT V%d", V);

    

}